### Configuration Variables ###
GINB_PATH: /home/hydro/ginotebook

### SSL Configuration Variables ###
FQDN_OR_IP: localhost
SSL_CERT_FILE: hydrodev-vb.example.org.cert
SSL_KEY_FILE: hydrodev-vb.example.org.key
GINB_SSL_DIR: /home/hydro/hs-certs

### nginx Configuration Variables ###
GINB_NGINX_DIR: /home/hydro/ginotebook/nginx
GINB_BASE_IMG: sshd_base
GINB_NGINX_IMG: ginb-nginx-img
GINB_NGINX: ginb-nginx

### Container / Image Names ###
GINB_CNAME: ginotebook_ginotebook_1
GINB_IMG_NAME: ginotebook_ginotebook
